import json
from datetime import datetime, timezone

from sqlalchemy.ext.asyncio import AsyncSession

from logbook.services.summary import get_weekly_report


def _render_weekly_markdown(data: dict) -> str:
    """Render a weekly report as markdown."""
    week_start = data["week_start"][:10]
    week_end = data["week_end"][:10]

    lines = [
        f"# Weekly Report: {week_start} to {week_end}",
        "",
        f"**Log entries:** {data['total_log_entries']}  ",
        f"**Tasks completed:** {data['total_tasks_completed']}  ",
        f"**Tasks created:** {data['total_tasks_created']}  ",
        f"**Goals completed:** {data['total_goals_completed']}",
        "",
    ]

    # By project
    if data["by_project"]:
        lines.append("## Work by Project")
        lines.append("")
        for pid, entries in data["by_project"].items():
            project_name = data["project_names"].get(pid, "Unknown")
            lines.append(f"### {project_name}")
            lines.append("")
            for entry in entries:
                day = entry.created_at[:10]
                time = entry.created_at[11:16]
                meta = json.loads(entry.metadata_json) if entry.metadata_json else {}
                commit_note = ""
                if meta.get("commit"):
                    commit_note = f" (`{meta['commit'][:7]}`"
                    if meta.get("repo"):
                        commit_note += f" in {meta['repo']}"
                    commit_note += ")"
                lines.append(f"- **{day}** {time} — {entry.description}{commit_note}")
            lines.append("")

    # By day
    if data["days"]:
        lines.append("## Daily Breakdown")
        lines.append("")
        for day, entries in sorted(data["days"].items()):
            weekday = datetime.fromisoformat(day).strftime("%A")
            lines.append(f"### {weekday}, {day}")
            lines.append("")
            for entry in entries:
                time = entry.created_at[11:16]
                lines.append(f"- {time} — {entry.description}")
            lines.append("")

    # Tasks completed
    if data["tasks_completed"]:
        lines.append("## Tasks Completed")
        lines.append("")
        for task in data["tasks_completed"]:
            completed = task.completed_at[:10] if task.completed_at else ""
            lines.append(f"- [x] {task.title} ({task.priority}) — completed {completed}")
        lines.append("")

    # Tasks created
    if data["tasks_created"]:
        lines.append("## Tasks Created")
        lines.append("")
        for task in data["tasks_created"]:
            status_marker = "x" if task.status == "done" else " "
            lines.append(f"- [{status_marker}] {task.title} ({task.priority}) — {task.status}")
        lines.append("")

    # Goals completed
    if data["goals_completed"]:
        lines.append("## Goals Completed")
        lines.append("")
        for goal in data["goals_completed"]:
            lines.append(f"- {goal.title}")
        lines.append("")

    # Footer
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines.append("---")
    lines.append(f"*Generated by Logbook on {now}*")
    lines.append("")

    return "\n".join(lines)


async def export_weekly_markdown(db: AsyncSession, weeks_back: int = 0) -> str:
    data = await get_weekly_report(db, weeks_back=weeks_back)
    return _render_weekly_markdown(data)
